### PR TITLE
Disable tracing on Android

### PR DESCRIPTION
**Pull request by Nizerlak**
Similarly to #52, there was also an issue with building on android (following steps in [this repo](https://github.com/YasuChiba/ros2-android-build))
I've just simply applied same solution as in #53.

### CODE REVIEW

**Comment by christophebedard** [comment]
Thanks for the PR! While I think installing LTTng on Android should be doable (unlike Windows), I think disabling it by default is reasonable.

We'll just have to wait until the Rolling freeze is lifted in a few days before merging. And then I think we could backport this to the new Iron branch as a bug fix.

**Comment by Nizerlak** [comment]
Should I do anything more regarding this PR?

**Comment by christophebedard** [comment]
> Should I do anything more regarding this PR?

No, I'll pick it up once Rolling is unfrozen.

**Comment by christophebedard** [comment]
Ah, one thing, though: the DCO check job is complaining because the commit author and the sign-off don't match:

* Commit author: `Przemysław Dąbrowski <57660090+Nizerlak@users.noreply.github.com>`
* Sign-off: `Przemyslaw Dabrowski <57660090+Nizerlak@users.noreply.github.com>`

Looks like the only difference is the ą/a. Would you mind changing the sign-off to match the commit author? Diacritics should be fine.

**Review by christophebedard — APPROVED** [review]

**Pull request merged**
