### PR TITLE
Run relevant test_tracetools tests with all instrumented rmw impls

### LINKED ISSUE #131: :farmer: test_pub_sub, test_publisher and test_subscription failures
# Description

These tests have been failing for a long time in Iron connext and fastrtps-dynamic.

Reference builds:
* [Ici__nightly-fastrtps-dynamic_ubuntu_jammy_amd64#155](https://build.ros2.org/job/Ici__nightly-fastrtps-dynamic_ubuntu_jammy_amd64/155)
* [Ici__nightly-connext_ubuntu_jammy_amd64#158](https://build.ros2.org/job/Ici__nightly-connext_ubuntu_jammy_amd64/158/)

Test regressions:
* [test_tracetools.test_tracetools.test.test_subscription.TestSubscription.test_all](https://build.ros2.org/job/Ici__nightly-connext_ubuntu_jammy_amd64/158/testReport/junit/test_tracetools.test_tracetools.test.test_subscription/TestSubscription/test_all/)
* [test_tracetools.test_tracetools.test.test_publisher.TestPublisher.test_all](https://build.ros2.org/job/Ici__nightly-connext_ubuntu_jammy_amd64/158/testReport/junit/test_tracetools.test_tracetools.test.test_publisher/TestPublisher/test_all/)
* [test_tracetools.test_tracetools.test.test_pub_sub.TestPubSub.test_all](https://build.ros2.org/job/Ici__nightly-connext_ubuntu_jammy_amd64/158/testReport/junit/test_tracetools.test_tracetools.test.test_pub_sub/TestPubSub/test_all/)
* [projectroot.test_pub_sub](https://build.ros2.org/job/Ici__nightly-connext_ubuntu_jammy_amd64/158/testReport/junit/(root)/projectroot/test_pub_sub/)

All three contain the same log output:

Log output:
```
11: =================================== FAILURES ===================================
11: __________________________ TestSubscription.test_all ___________________________
11: /tmp/ws/install_isolated/tracetools_test/lib/python3.10/site-packages/tracetools_test/case.py:110: in setUp
11:     self.assertSetEqual(all_event_names, set(self._event_names))
11: E   AssertionError: Items in the first set but not the second:
11: E   'ros2:rmw_subscription_init'
11: E   'ros2:rmw_take'
11: ----------------------------- Captured stdout call -----------------------------
11: [INFO] [launch]: All log files can be found below /home/buildfarm/.ros/log/2024-08-19-01-58-16-902022-a9e85b8b6b09-444099
11: [INFO] [launch]: Default logging verbosity is set to INFO
11: [INFO] [tracetools_launch.action]: Writing tracing session to: /tmp/session-test-subscription-20240819015816
11: [INFO] [test_ping-1]: process started with pid [444104]
11: [INFO] [test_pong-2]: process started with pid [444106]
11: [test_pong-2] [INFO] [1724061498.067881993] [test_pong]: [output] some random ping string
11: [test_ping-1] [INFO] [1724061498.068240921] [test_ping]: [output] some random pong string
11: [test_pong-2] RTI Connext DDS Non-commercial license is for academic, research, evaluation and personal use only. USE FOR COMMERCIAL PURPOSES IS PROHIBITED. See RTI_LICENSE.TXT for terms. Download free tools at rti.com/ncl. License issued to Non-Commercial User license@rti.com For non-production use only.
11: [test_pong-2] Expires on 00-jan-00 See www.rti.com for more information.
11: [test_pong-2] spinning
11: [INFO] [test_pong-2]: process has finished cleanly [pid 444106]
11: [test_ping-1] RTI Connext DDS Non-commercial license is for academic, research, evaluation and personal use only. USE FOR COMMERCIAL PURPOSES IS PROHIBITED. See RTI_LICENSE.TXT for terms. Download free tools at rti.com/ncl. License issued to Non-Commercial User license@rti.com For non-production use only.
11: [test_ping-1] Expires on 00-jan-00 See www.rti.com for more information.
11: [test_ping-1] spinning
11: [INFO] [test_ping-1]: process has finished cleanly [pid 444104]
11: TRACE DIRECTORY: /tmp/session-test-subscription-20240819015816
11: - generated xml file: /tmp/ws/test_results/test_tracetools/test_subscription.xunit.xml -
11: 
11: ---------- coverage: platform linux, python 3.10.12-final-0 ----------
11: 
11: =========================== short test summary info ============================
11: FAILED test/test_subscription.py::TestSubscription::test_all - AssertionError...
11: ============================== 1 failed in 2.52s ===============================
11: -- run_test.py: return code 1
11: -- run_test.py: verify result file '/tmp/ws/test_results/test_tracetools/test_subscription.xunit.xml'
3/3 Test #11: test_subscription ................***Failed    3.22 sec



The following tests FAILED:
	  8 - test_pub_sub (Failed)
	  9 - test_publisher (Failed)
	 11 - test_subscription (Failed)
```

### PR DESCRIPTION
**Pull request by christophebedard**
Fixes #131

This is ~~equivalent~~ similar to #116 but for Jazzy.

See explanation in #132. For Jazzy, `rmw_connextdds` is supported (compared to Iron), but `rmw_fastrtps_dynamic_cpp` is not (compared to Rolling).

### CODE REVIEW

**Comment by christophebedard** [comment]
I don't think we have a manual version of the Jci__nightly-fastrtps-dynamic_ubuntu_noble_amd64 job, so I'll just run manual CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21727/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16002/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1232/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22430/)

I did test locally by setting `RMW_IMPLEMENTATIONS=rmw_fastrtps_dynamic_cpp` when running `colcon build` and the tests were skipped.

**Comment by christophebedard** [comment]
I think the failure in `test_pub_sub__rmw_connextdds` on RHEL is a flake and should be resolved by backporting #125 to Jazzy.

**Comment by christophebedard** [comment]
> I think the failure in `test_pub_sub__rmw_connextdds` on RHEL is a flake and should be resolved by backporting #125 to Jazzy: #135.

Done. I rebased this. Re-running CI just to be sure:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21742/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16016/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1247/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22445/)

**Comment by christophebedard** [comment]
@clalancette @fujitatomoya can one of you review this?

**Review by clalancette — APPROVED** [review]

**Pull request merged**
