### PR TITLE
Switch to ament_generate_version_header for tracetools

### PR DESCRIPTION
**Pull request by christophebedard**
Instead of manually defining a private compile definition.

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]

**Comment by christophebedard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20869/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15172/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21551/)

**Review by fujitatomoya — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@christophebedard windows failing https://ci.ros2.org/job/ci_windows/21551/console, can you check it?

**Comment by christophebedard** [comment]
Weird. I think it might be due to the header `install()` having `DIRECTORY ${PROJECT_BINARY_DIR}/include/` but not `DIRECTORY  include/` and/or due to the generated `version.h` file being under `build/tracetools/ament_generate_version_header/tracetools/tracetools/version.h` instead of the usual (e.g., `build/tracetools/include/tracetools/config.h`).

The private definition for the version didn't exist anyway if `TRACETOOLS_DISABLED`, which is true on Windows, so we can just skip it.

**Comment by christophebedard** [comment]
I'll assume that the new change will be acceptable and kick off another round of CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20871/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15174/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21553/)

**Pull request merged**
