### PR TITLE
Fix Python not being found for lttngpy in Windows debug mode

### LINKED ISSUE #86: lttngpy fails to build on Windows Debug
Looking at the nightly builds, it looks like the new `lttngpy` package fails to build on Windows Debug: https://ci.ros2.org/view/packaging/job/packaging_windows_debug/2070/

In particular, the end of the trace says:

```
--- output: lttngpy
Not searching for unused variables given on the command line.
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.20348.
-- The C compiler identification is MSVC 19.29.30153.0
-- The CXX compiler identification is MSVC 19.29.30153.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 2.3.2 (C:/ci/ws/install/share/ament_cmake/cmake)
-- Found Python3: C:/Python38/python.exe (found version "3.8.3") found components: Interpreter 
-- Found Python3: C:/Python38/python.exe (found version "3.8.3") found components: Interpreter Development Development.Module Development.Embed 
-- Found pybind11_vendor: 3.1.1 (C:/ci/ws/install/share/pybind11_vendor/cmake)
-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Success
-- Found pybind11: C:/ci/ws/install/opt/pybind11_vendor/include (found version "2.9.1")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ci/ws/build/lttngpy
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Checking Build System

  Building Custom Rule C:/ci/ws/src/ros2/ros2_tracing/lttngpy/CMakeLists.txt

  running egg_info

  creating lttngpy.egg-info

  writing lttngpy.egg-info\PKG-INFO

  writing dependency_links to lttngpy.egg-info\dependency_links.txt

  writing top-level names to lttngpy.egg-info\top_level.txt

  writing manifest file 'lttngpy.egg-info\SOURCES.txt'

  reading manifest file 'lttngpy.egg-info\SOURCES.txt'

  writing manifest file 'lttngpy.egg-info\SOURCES.txt'

  Building Custom Rule C:/ci/ws/src/ros2/ros2_tracing/lttngpy/CMakeLists.txt

  Building Custom Rule C:/ci/ws/src/ros2/ros2_tracing/lttngpy/CMakeLists.txt

  _lttngpy_pybind11.cpp

  status.cpp

LINK : fatal error LNK1104: cannot open file 'python38.lib' [C:\ci\ws\build\lttngpy\_lttngpy_pybind11.vcxproj]

---
Failed   <<< lttngpy [41.5s, exited with code 1]
```

@christophebedard can you take a look?

### PR DESCRIPTION
**Pull request by christophebedard**
Closes #86

I found this fix in a few other packages that use Python in CMake.

### CODE REVIEW

**Comment by clalancette** [comment]
> Trying a packaging_windows_debug job first:

In general, we prefer not to use the `packaging_*` jobs for debugging.  That's just so that they have a relatively "clean" history of what has happened nightly.  Instead, we prefer to use https://ci.ros2.org/view/All/job/test_packaging_windows/ .

In this case, it has already been done, so you can just let it run.  But just for future reference.

**Comment by christophebedard** [comment]
> > Trying a packaging_windows_debug job first:
> 
> In general, we prefer not to use the `packaging_*` jobs for debugging. That's just so that they have a relatively "clean" history of what has happened nightly. Instead, we prefer to use https://ci.ros2.org/view/All/job/test_packaging_windows/ .
> 
> In this case, it has already been done, so you can just let it run. But just for future reference.

Oh, sorry! I should've looked for a `test_*` equivalent.

Seems like `lttngpy` now builds successfully, so let's run full CI, including a Windows debug job:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20062/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14515/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20782/)
* Windows debug [Build Status](http://ci.ros2.org/job/ci_windows/20783/)

**Comment by clalancette** [comment]
> Seems like `lttngpy` now builds successfully, so let's run full CI, including a Windows debug job:

Just so you know; we have other, unrelated failures in Windows Debug CI at the moment.  So I expect that job will fail, but it should get past the compilation phase and into running tests before doing so.

**Comment by christophebedard** [comment]
It ended up passing, probably because I only tested `--packages-above lttngpy`.

**Pull request merged**
