### PR TITLE
Switch to target_link_libraries in test_tracetools.

### PR DESCRIPTION
**Pull request by clalancette**
While we are in here, mark all dependencies as test_depend (since this is a test-only package).

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19878/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14364/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20587/)

**Comment by christophebedard** [comment]
It looks like this breaks something in `test_ros2trace`, which relies on `test_tracetools`. I see the same failure in GitHub CI: https://github.com/ros2/ros2_tracing/actions/runs/6998187248/job/19035964490?pr=83#step:4:28701. I'll try to take a look today.

**Comment by clalancette** [comment]
> [`test_ros2trace` uses node executables from `test_tracetools`](https://github.com/ros2/ros2_tracing/blob/0d9883c183244d4ac8f35e0e759b0642f5f91014/test_ros2trace/test/test_ros2trace/test_trace.py#L217-L234), so `test_ros2trace` depended on `test_tracetools` `<[exec_]depend>`ing on `std_msgs`, `rclcpp`, and friends: https://github.com/ros2/ros2_tracing/actions/runs/6998187248/job/19035964490?pr=83#step:4:28395

Thanks for this analysis, it was helpful.

While looking at this, it occurred to me that there was another solution here.  And that is to export the dependencies that we need from `test_tracetools` so that colcon will properly setup the environment.  That way we can keep all of the dependencies as `test_depend`, but just export the ones that are needed externally.  I've done that in 819c592, and it seems to work in my testing.

Thoughts on this approach?

**Comment by christophebedard** [comment]
Sorry for the delay. That's a good idea.

However, if we want `test_tracetools` test node executables to be used by tests in other `test_*` packages, then we should do this for `std_srvs` and `rclcpp_lifecycle` too (I think those are the other required dependencies if a downstream package were to use all nodes). Explicitly mentioning `test_ros2trace` in `test_tracetools` and limiting the `<build_export_depend>` to just those dependencies feels a bit weird, but I don't really mind. We can always change it in the future; it's just a test package.

**Review by christophebedard — APPROVED** [review]

**Comment by clalancette** [comment]
> However, if we want `test_tracetools` test node executables to be used by tests in other `test_*` packages, then we should do this for `std_srvs` and `rclcpp_lifecycle` too (I think those are the other required dependencies if a downstream package were to use all nodes). Explicitly mentioning `test_ros2trace` in `test_tracetools` and limiting the `<build_export_depend>` to just those dependencies feels a bit weird (i.e., `test_tracetools` ideally shouldn't know about downstream packages), but I don't really mind. We can always change it in the future; it's just a test package.

Good points.  I've updated it now to `build_export_depend` all of the necessary dependencies, and I've also updated the language to be less specific to test_ros2trace.  I'm going to pull this out of draft status now and run CI on it, thanks for the review!

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19909/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14388/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20617/)

**Review by christophebedard — APPROVED** [review]
Looks good!

**Pull request merged**
