### PR TITLE
Replace all occurences of index.ros.org

### PR DESCRIPTION
**Pull request by clalancette**

### CODE REVIEW

**Review by christophebedard — APPROVED** [review]

**Review by ahcorde — APPROVED** [review]

**Comment by christophebedard** [comment]
Are we allowed to merge this now given that it is docs-related?

**Review by wjwwood — APPROVED** [review]

**Comment by wjwwood** [comment]
@christophebedard yeah, I would say so.

**Comment by christophebedard** [comment]
This changes `package.xml` ifles, so:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20874/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15177/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21556/)

**Comment by christophebedard** [comment]
Linux x86_64 and aarch64 CI jobs passed, so I'll call that "good enough."

**Pull request merged**
